





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;


namespace Hedgehog.Website.Core.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }
	}
}




namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IEvent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Event</para>	
	/// <para>ID: 10a1f8f9-d9a8-4731-8c4f-452350604054</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEventConstants.TemplateIdString)]
	public partial interface IEvent : IGlassBase , global::Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface.IFeature, global::Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface.IPageTitles
	{
								/// <summary>
					/// The EventDate field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 322266cb-e5eb-4be4-9497-a65493eb0ef7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IEventConstants.EventDateFieldName)]
					DateTime EventDate  {get; set;}
			
				}


	public static partial class IEventConstants{

			public const string TemplateIdString = "10a1f8f9-d9a8-4731-8c4f-452350604054";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Event";

					
			public static readonly ID EventDateFieldId = new ID("322266cb-e5eb-4be4-9497-a65493eb0ef7");
			public const string EventDateFieldName = "EventDate";
			
					
			public static readonly ID IFeatureAbstractFieldId = new ID("2dcafc6b-6f89-425f-870a-9b152051a419");
			public const string IFeatureAbstractFieldName = "IFeatureAbstract";
			
					
			public static readonly ID IFeatureLargeImageFieldId = new ID("54d4b848-05dc-49d4-968f-019e9f462722");
			public const string IFeatureLargeImageFieldName = "IFeatureLargeImage";
			
					
			public static readonly ID IFeatureSmallImageFieldId = new ID("ddc6edd5-7966-4e6c-91a5-8f8986189429");
			public const string IFeatureSmallImageFieldName = "IFeatureSmallImage";
			
					
			public static readonly ID IPageTitlesLongFieldId = new ID("72093e7c-b257-45f9-919e-ed85da531d92");
			public const string IPageTitlesLongFieldName = "IPageTitlesLong";
			
					
			public static readonly ID IPageTitlesShortFieldId = new ID("f1b47d72-9dba-4fa7-9f36-d8dce5e284f8");
			public const string IPageTitlesShortFieldName = "IPageTitlesShort";
			
			

	}

	
	/// <summary>
	/// Event
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Event</para>	
	/// <para>ID: 10a1f8f9-d9a8-4731-8c4f-452350604054</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEventConstants.TemplateIdString)]
	public partial class Event  : GlassBase, IEvent 
	{
	   
						/// <summary>
				/// The EventDate field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 322266cb-e5eb-4be4-9497-a65493eb0ef7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEventConstants.EventDateFieldName)]
				public virtual DateTime EventDate  {get; set;}
					
						/// <summary>
				/// The IFeatureAbstract field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 2dcafc6b-6f89-425f-870a-9b152051a419</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEventConstants.IFeatureAbstractFieldName)]
				public virtual string IFeatureAbstract  {get; set;}
					
						/// <summary>
				/// The IFeatureLargeImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 54d4b848-05dc-49d4-968f-019e9f462722</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEventConstants.IFeatureLargeImageFieldName)]
				public virtual Image IFeatureLargeImage  {get; set;}
					
						/// <summary>
				/// The IFeatureSmallImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: ddc6edd5-7966-4e6c-91a5-8f8986189429</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEventConstants.IFeatureSmallImageFieldName)]
				public virtual Image IFeatureSmallImage  {get; set;}
					
						/// <summary>
				/// The IPageTitlesLong field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 72093e7c-b257-45f9-919e-ed85da531d92</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEventConstants.IPageTitlesLongFieldName)]
				public virtual string IPageTitlesLong  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShort field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1b47d72-9dba-4fa7-9f36-d8dce5e284f8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEventConstants.IPageTitlesShortFieldName)]
				public virtual string IPageTitlesShort  {get; set;}
					
			
	}
}



namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Home</para>	
	/// <para>ID: 1f37fab9-6ca1-4dff-94cf-78526d705494</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)]
	public partial interface IHome : IGlassBase , global::Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface.IPageTitles
	{
								/// <summary>
					/// The HomeSiteLogo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 929a6c09-21fd-4da2-8a37-eb04bb8f75ea</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.HomeSiteLogoFieldName)]
					Image HomeSiteLogo  {get; set;}
			
								/// <summary>
					/// The HomeSiteName field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 3faa27de-dab3-48b2-9df7-27f421614149</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.HomeSiteNameFieldName)]
					string HomeSiteName  {get; set;}
			
				}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "1f37fab9-6ca1-4dff-94cf-78526d705494";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

					
			public static readonly ID HomeSiteLogoFieldId = new ID("929a6c09-21fd-4da2-8a37-eb04bb8f75ea");
			public const string HomeSiteLogoFieldName = "HomeSiteLogo";
			
					
			public static readonly ID HomeSiteNameFieldId = new ID("3faa27de-dab3-48b2-9df7-27f421614149");
			public const string HomeSiteNameFieldName = "HomeSiteName";
			
					
			public static readonly ID IPageTitlesLongFieldId = new ID("72093e7c-b257-45f9-919e-ed85da531d92");
			public const string IPageTitlesLongFieldName = "IPageTitlesLong";
			
					
			public static readonly ID IPageTitlesShortFieldId = new ID("f1b47d72-9dba-4fa7-9f36-d8dce5e284f8");
			public const string IPageTitlesShortFieldName = "IPageTitlesShort";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Home</para>	
	/// <para>ID: 1f37fab9-6ca1-4dff-94cf-78526d705494</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)]
	public partial class Home  : GlassBase, IHome 
	{
	   
						/// <summary>
				/// The HomeSiteLogo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 929a6c09-21fd-4da2-8a37-eb04bb8f75ea</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.HomeSiteLogoFieldName)]
				public virtual Image HomeSiteLogo  {get; set;}
					
						/// <summary>
				/// The HomeSiteName field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3faa27de-dab3-48b2-9df7-27f421614149</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.HomeSiteNameFieldName)]
				public virtual string HomeSiteName  {get; set;}
					
						/// <summary>
				/// The IPageTitlesLong field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 72093e7c-b257-45f9-919e-ed85da531d92</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.IPageTitlesLongFieldName)]
				public virtual string IPageTitlesLong  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShort field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1b47d72-9dba-4fa7-9f36-d8dce5e284f8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.IPageTitlesShortFieldName)]
				public virtual string IPageTitlesShort  {get; set;}
					
			
	}
}



namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface
{


 	/// <summary>
	/// IFeature Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Interface/IFeature</para>	
	/// <para>ID: 2c441863-d10c-497c-aff3-1a2fc303a3cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFeatureConstants.TemplateIdString)]
	public partial interface IFeature : IGlassBase 
	{
								/// <summary>
					/// The IFeatureAbstract field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 2dcafc6b-6f89-425f-870a-9b152051a419</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureConstants.IFeatureAbstractFieldName)]
					string IFeatureAbstract  {get; set;}
			
								/// <summary>
					/// The IFeatureLargeImage field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 54d4b848-05dc-49d4-968f-019e9f462722</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureConstants.IFeatureLargeImageFieldName)]
					Image IFeatureLargeImage  {get; set;}
			
								/// <summary>
					/// The IFeatureSmallImage field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ddc6edd5-7966-4e6c-91a5-8f8986189429</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureConstants.IFeatureSmallImageFieldName)]
					Image IFeatureSmallImage  {get; set;}
			
				}


	public static partial class IFeatureConstants{

			public const string TemplateIdString = "2c441863-d10c-497c-aff3-1a2fc303a3cd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "IFeature";

					
			public static readonly ID IFeatureAbstractFieldId = new ID("2dcafc6b-6f89-425f-870a-9b152051a419");
			public const string IFeatureAbstractFieldName = "IFeatureAbstract";
			
					
			public static readonly ID IFeatureLargeImageFieldId = new ID("54d4b848-05dc-49d4-968f-019e9f462722");
			public const string IFeatureLargeImageFieldName = "IFeatureLargeImage";
			
					
			public static readonly ID IFeatureSmallImageFieldId = new ID("ddc6edd5-7966-4e6c-91a5-8f8986189429");
			public const string IFeatureSmallImageFieldName = "IFeatureSmallImage";
			
			

	}

}

























namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IEventLanding Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/EventLanding</para>	
	/// <para>ID: 78ca1ccd-13f2-4886-bd8c-4e81f0f9bfae</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEventLandingConstants.TemplateIdString)]
	public partial interface IEventLanding : IGlassBase 
	{
				}


	public static partial class IEventLandingConstants{

			public const string TemplateIdString = "78ca1ccd-13f2-4886-bd8c-4e81f0f9bfae";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "EventLanding";

			

	}

	
	/// <summary>
	/// EventLanding
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/EventLanding</para>	
	/// <para>ID: 78ca1ccd-13f2-4886-bd8c-4e81f0f9bfae</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEventLandingConstants.TemplateIdString)]
	public partial class EventLanding  : GlassBase, IEventLanding 
	{
	   
			
	}
}





namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// ILanding Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Landing</para>	
	/// <para>ID: 93508df3-d5dc-4ade-8b5b-0725cb9e92a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILandingConstants.TemplateIdString)]
	public partial interface ILanding : IGlassBase , global::Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Base.IPageBase, global::Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface.IFeature
	{
				}


	public static partial class ILandingConstants{

			public const string TemplateIdString = "93508df3-d5dc-4ade-8b5b-0725cb9e92a3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Landing";

					
			public static readonly ID IPageTitlesLongFieldId = new ID("72093e7c-b257-45f9-919e-ed85da531d92");
			public const string IPageTitlesLongFieldName = "IPageTitlesLong";
			
					
			public static readonly ID IPageTitlesShortFieldId = new ID("f1b47d72-9dba-4fa7-9f36-d8dce5e284f8");
			public const string IPageTitlesShortFieldName = "IPageTitlesShort";
			
					
			public static readonly ID IFeatureAbstractFieldId = new ID("2dcafc6b-6f89-425f-870a-9b152051a419");
			public const string IFeatureAbstractFieldName = "IFeatureAbstract";
			
					
			public static readonly ID IFeatureLargeImageFieldId = new ID("54d4b848-05dc-49d4-968f-019e9f462722");
			public const string IFeatureLargeImageFieldName = "IFeatureLargeImage";
			
					
			public static readonly ID IFeatureSmallImageFieldId = new ID("ddc6edd5-7966-4e6c-91a5-8f8986189429");
			public const string IFeatureSmallImageFieldName = "IFeatureSmallImage";
			
			

	}

	
	/// <summary>
	/// Landing
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Landing</para>	
	/// <para>ID: 93508df3-d5dc-4ade-8b5b-0725cb9e92a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILandingConstants.TemplateIdString)]
	public partial class Landing  : GlassBase, ILanding 
	{
	   
						/// <summary>
				/// The IPageTitlesLong field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 72093e7c-b257-45f9-919e-ed85da531d92</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IPageTitlesLongFieldName)]
				public virtual string IPageTitlesLong  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShort field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1b47d72-9dba-4fa7-9f36-d8dce5e284f8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IPageTitlesShortFieldName)]
				public virtual string IPageTitlesShort  {get; set;}
					
						/// <summary>
				/// The IFeatureAbstract field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 2dcafc6b-6f89-425f-870a-9b152051a419</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IFeatureAbstractFieldName)]
				public virtual string IFeatureAbstract  {get; set;}
					
						/// <summary>
				/// The IFeatureLargeImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 54d4b848-05dc-49d4-968f-019e9f462722</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IFeatureLargeImageFieldName)]
				public virtual Image IFeatureLargeImage  {get; set;}
					
						/// <summary>
				/// The IFeatureSmallImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: ddc6edd5-7966-4e6c-91a5-8f8986189429</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IFeatureSmallImageFieldName)]
				public virtual Image IFeatureSmallImage  {get; set;}
					
			
	}
}


namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface
{


 	/// <summary>
	/// IPageTitles Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Interface/IPageTitles</para>	
	/// <para>ID: a0182cc7-2006-47c8-86b8-bed29b9a70bf</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageTitlesConstants.TemplateIdString)]
	public partial interface IPageTitles : IGlassBase 
	{
								/// <summary>
					/// The IPageTitlesLong field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 72093e7c-b257-45f9-919e-ed85da531d92</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageTitlesConstants.IPageTitlesLongFieldName)]
					string IPageTitlesLong  {get; set;}
			
								/// <summary>
					/// The IPageTitlesShort field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f1b47d72-9dba-4fa7-9f36-d8dce5e284f8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageTitlesConstants.IPageTitlesShortFieldName)]
					string IPageTitlesShort  {get; set;}
			
				}


	public static partial class IPageTitlesConstants{

			public const string TemplateIdString = "a0182cc7-2006-47c8-86b8-bed29b9a70bf";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "IPageTitles";

					
			public static readonly ID IPageTitlesLongFieldId = new ID("72093e7c-b257-45f9-919e-ed85da531d92");
			public const string IPageTitlesLongFieldName = "IPageTitlesLong";
			
					
			public static readonly ID IPageTitlesShortFieldId = new ID("f1b47d72-9dba-4fa7-9f36-d8dce5e284f8");
			public const string IPageTitlesShortFieldName = "IPageTitlesShort";
			
			

	}

}



















namespace Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Base
{


 	/// <summary>
	/// IPageBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Base/PageBase</para>	
	/// <para>ID: e562a63d-54d5-4383-b708-6e1b29547012</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString)]
	public partial interface IPageBase : IGlassBase , global::Hedgehog.Website.Core.Models.sitecore.templates.Sugnl.Interface.IPageTitles
	{
				}


	public static partial class IPageBaseConstants{

			public const string TemplateIdString = "e562a63d-54d5-4383-b708-6e1b29547012";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "PageBase";

					
			public static readonly ID IPageTitlesLongFieldId = new ID("72093e7c-b257-45f9-919e-ed85da531d92");
			public const string IPageTitlesLongFieldName = "IPageTitlesLong";
			
					
			public static readonly ID IPageTitlesShortFieldId = new ID("f1b47d72-9dba-4fa7-9f36-d8dce5e284f8");
			public const string IPageTitlesShortFieldName = "IPageTitlesShort";
			
			

	}

	
	/// <summary>
	/// PageBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Base/PageBase</para>	
	/// <para>ID: e562a63d-54d5-4383-b708-6e1b29547012</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString)]
	public partial class PageBase  : GlassBase, IPageBase 
	{
	   
						/// <summary>
				/// The IPageTitlesLong field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 72093e7c-b257-45f9-919e-ed85da531d92</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.IPageTitlesLongFieldName)]
				public virtual string IPageTitlesLong  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShort field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1b47d72-9dba-4fa7-9f36-d8dce5e284f8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.IPageTitlesShortFieldName)]
				public virtual string IPageTitlesShort  {get; set;}
					
			
	}
}






